#!/bin/sh
prefix=`dirname $(readlink $0 || echo $0)`
java --module-path="${prefix}/lib" -Xmx1500m \
    @igv.args \
    --class-path="${prefix}/lib_classpath/*" \
    -Dsun.java2d.uiScale=2 \
    --module=org.igv/org.broad.igv.tools.IgvTools  gui
